version: '3'

services:
  django:
    build: ./innotter_django
    entrypoint:
      - ./django_entrypoint.sh
    volumes:
      - ./innotter_django:/innotter_django
    env_file:
      - ./innotter_django/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: pgdb
    image: postgres
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - DB_HOST=postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    links:
      - postgres:db
    env_file:
      - ./innotter_django/.env
    ports:
      - "5050:80"

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    restart: always
    build: ./innotter_django
    entrypoint:
      - ./celery_entrypoint.sh
    volumes:
      - ./innotter_django:/innotter_django
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq3:5672/
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq3:5672/
    env_file:
      - ./innotter_django/.env
    links:
      - localstack
      - rabbitmq3
      - django

  localstack:
    container_name: localstack
    environment:
      - LOCALSTACK_HOSTNAME=localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
