# Generated by Django 4.1 on 2022-10-24 11:49

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_s3_path',
            field=models.ImageField(blank=True, storage=core.storages.PublicMediaStorage, upload_to=''),
        ),
    ]
